# Usar a imagem oficial do Node.js como base
FROM node:alpine

# Criar o diretório de trabalho no contêiner
WORKDIR /app

# Copiar os arquivos de configuração do NestJS e o arquivo package.json
COPY package*.json ./

# Instalar as dependências do aplicativo
RUN npm install

# Copiar o código do aplicativo para o contêiner
COPY . .

# Expôr a porta do aplicativo
EXPOSE 3000

# Comando para executar o aplicativo
CMD ["npm", "run", "start:prod"]
